export const profile = { name: 'Maumorell', whatsapp: '5493794934184', instagram: 'maumorell', portrait: '' };
export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, '');
export const contactUrl = `https://wa.me/${profile.whatsapp}?text=${encodeURIComponent('Hola Mau, me gustaría conversar sobre un proyecto.')}`;
export const projects = [
 { slug: 'connexa', name: 'Connexa', category: 'REAL ESTATE · PRODUCTO DIGITAL', type: 'Next.js', number: '01', color: 'lime', headline: 'De propiedades sueltas a una operación conectada.', description: 'Una plataforma inmobiliaria construida desde cero. Catálogo público, gestión de propiedades y herramientas para el trabajo comercial, en un mismo ecosistema.', challenge: 'Conectar la experiencia de quien busca una propiedad con la operación diaria de quien la comercializa.', approach: 'Desarrollo con Next.js y Supabase, gestión de imágenes, catálogo y un módulo CRM separado para evolucionar la operación comercial.', scope: ['Catálogo y fichas de propiedades', 'Administración y gestión de contenido', 'CRM, agenda y seguimiento comercial', 'Optimización de entrega de imágenes'], note: 'La exploración de conversaciones omnicanal está en etapa de demo: no implica canales de mensajería conectados en producción.', stack: ['Next.js', 'TypeScript', 'Supabase', 'CRM'] },
 { slug: 'minifimy', name: 'MiniFimy', category: 'E-COMMERCE · HEADLESS', type: 'WooCommerce', number: '02', color: 'pink', headline: 'El poder de WooCommerce. Una experiencia a medida.', description: 'Una tienda con frontend en Next.js y WooCommerce como motor comercial. Una experiencia propia, con atención al catálogo, las variantes y los precios.', challenge: 'Ofrecer una experiencia de compra personalizada conservando la administración de productos de WooCommerce.', approach: 'Frontend desacoplado e integración con las APIs de WooCommerce. Trabajo sobre la carga del catálogo y la consistencia de precios de productos variables.', scope: ['Storefront en Next.js', 'Integración con WooCommerce y WordPress', 'Catálogo, variantes y precios', 'Optimización de consultas y caché'], note: 'Se describe el trabajo realizado, sin atribuir incrementos de ventas ni métricas comerciales no medidas.', stack: ['Next.js', 'WooCommerce', 'WordPress', 'API'] },
 { slug: 'alojamiento-buenos-aires', name: 'Alojamiento BA', category: 'HOSPITALITY · DESARROLLO A MEDIDA', type: 'Next.js', number: '03', color: 'blue', headline: 'Encontrar un lugar empieza con una buena experiencia.', description: 'Un producto para descubrir alojamientos en Buenos Aires. Catálogo, contenido y gestión de medios adaptados a su propia operación.', challenge: 'Presentar alojamientos con información clara y una experiencia consistente entre catálogo y detalle.', approach: 'Desarrollo de catálogo y páginas de alojamiento, gestión editorial y de imágenes, con Next.js y Supabase.', scope: ['Catálogo de alojamientos', 'Galerías y fichas de detalle', 'Gestión editorial', 'Experiencia responsive'], note: 'Una implementación independiente, con sus propios datos y reglas de administración.', stack: ['Next.js', 'Supabase', 'TypeScript', 'UI / UX'] },
 { slug: 'mares', name: 'Studio Marès', category: 'PROPTECH · IMÁGENES CON IA', type: 'Next.js', number: '04', color: 'sand', headline: 'El potencial de un espacio, en su mejor imagen.', description: 'Una plataforma para trabajar la presentación visual de propiedades y alojamientos con inteligencia artificial. Proyectos, fotografías y versiones en una experiencia de edición propia.', challenge: 'Mejorar la presentación de un espacio sin perder su identidad, y ordenar las imágenes y versiones dentro de un flujo de trabajo claro.', approach: 'Desarrollo de una plataforma con Next.js, gestión de proyectos y medios, y un flujo de edición de imágenes con IA. Reglas de fidelidad para conservar arquitectura, distribución y características reales de cada propiedad.', scope: ['Plataforma y editor con Next.js', 'Edición visual de propiedades con IA', 'Gestión de proyectos, fotos y versiones', 'Selección de portadas y experiencia responsive'], note: 'El caso describe el desarrollo del producto y sus controles de edición. No atribuye resultados comerciales ni garantiza la fidelidad de cada generación automática.', stack: ['Next.js', 'TypeScript', 'Supabase', 'IA'] },
 { slug: 'courts', name: 'Courts', category: 'RETAIL REGIONAL · ADOBE COMMERCE', type: 'Magento', number: '05', color: 'orange', headline: 'Un catálogo regional que tiene que responder a cada mercado.', description: 'E-commerce regional sobre Magento / Adobe Commerce, con catálogos extensos, financiación, promociones y experiencias adaptadas por país.', challenge: 'Evolucionar una operación de comercio electrónico multipaís sin perder continuidad, trazabilidad ni velocidad en la experiencia de compra.', approach: 'Trabajo sobre Adobe Commerce, integraciones y scripts de terceros, observabilidad y diagnóstico de rendimiento para priorizar mejoras con evidencia.', scope: ['Magento / Adobe Commerce', 'Experiencia de catálogo y compra', 'Integraciones y scripts de terceros', 'Performance y observabilidad'], note: 'El caso describe áreas de trabajo técnico. No publica información interna ni atribuye métricas comerciales no verificadas.', stack: ['Magento', 'Adobe Commerce', 'New Relic', 'Integraciones'] },
 { slug: 'imeca', name: 'Imeca', category: 'E-COMMERCE B2B · SHOPIFY', type: 'Shopify', number: '06', color: 'yellow', headline: 'Un catálogo técnico también puede sentirse simple.', description: 'Tienda Shopify para materiales, herrajes y soluciones de remodelación, con un catálogo amplio pensado para clientes y profesionales.', challenge: 'Hacer que miles de productos técnicos sean fáciles de descubrir, comparar y comprar desde distintos dispositivos.', approach: 'Evolución del storefront y del contenido comercial dentro de Shopify, cuidando colecciones, navegación, producto y consistencia responsive.', scope: ['Storefront en Shopify', 'Colecciones y catálogo técnico', 'Experiencia de producto', 'Contenido comercial responsive'], note: 'La descripción se limita al alcance de experiencia y plataforma; no atribuye resultados de negocio.', stack: ['Shopify', 'Liquid', 'E-commerce', 'UX'] },
 { slug: 'a-caballo-regalado', name: 'A Caballo Regalado', category: 'REGALOS · EMPRETIENDA', type: 'Empretienda', number: '07', color: 'violet', headline: 'Regalar empieza mucho antes de abrir el paquete.', description: 'Tienda online de regalos desarrollada sobre Empretienda, con catálogo, identidad de marca y una experiencia directa para elegir y comprar.', challenge: 'Presentar productos con personalidad y reducir la fricción entre descubrir una idea, elegirla y concretar la compra.', approach: 'Configuración y evolución de la tienda en Empretienda, organización del catálogo, contenido de marca y ajustes de experiencia responsive.', scope: ['Tienda en Empretienda', 'Catálogo y categorías', 'Contenido e identidad comercial', 'Experiencia mobile'], note: 'La URL personalizada indicada no resuelve actualmente; el enlace usa la tienda pública activa alojada en Empretienda.', stack: ['Empretienda', 'E-commerce', 'Contenido', 'UX'] },
];
export const services = [
 { title: 'Productos digitales a medida', text: 'Convertí una operación que depende de planillas y herramientas sueltas en una plataforma propia.', tags: 'NEXT.JS / REACT / SUPABASE', items: ['Webs y plataformas inmobiliarias', 'Paneles de gestión y CRM', 'Integraciones y automatización'] },
 { title: 'E-commerce que acompaña tu negocio', text: 'Una tienda tiene que ser fácil de comprar y de operar. Trabajo en ambas partes de la experiencia.', tags: 'MAGENTO / WOOCOMMERCE / HEADLESS', items: ['Tiendas y experiencias de compra', 'Catálogos e integraciones', 'Evolución de plataformas existentes'] },
 { title: 'Una base lista para crecer', text: 'Rendimiento, SEO técnico y mantenimiento para que tu web siga siendo una herramienta de trabajo.', tags: 'PERFORMANCE / SEO / EVOLUCIÓN', items: ['Auditorías con prioridades claras', 'Arquitectura e indexación', 'Mejoras y acompañamiento técnico'] },
];
export const faqs = [
 ['¿Podés desarrollar mi proyecto desde cero?', 'Sí. Podemos empezar por tu objetivo comercial, definir el alcance y construir la experiencia, el frontend y la gestión. Primero identificamos qué necesita la primera versión y qué puede evolucionar después.'],
 ['¿Trabajás sobre una tienda o web que ya existe?', 'Sí. Trabajo con Magento / Adobe Commerce, WooCommerce y proyectos Next.js existentes. El primer paso es revisar la plataforma y priorizar las mejoras según su impacto y complejidad.'],
 ['¿Qué incluye el trabajo de SEO?', 'Una base técnica con HTML semántico, metadatos, estructura de enlaces, sitemap e indexación. El contenido se organiza alrededor de lo que buscan tus clientes. El posicionamiento requiere continuidad; no se prometen posiciones específicas.'],
 ['¿Cuánto cuesta y cuánto tiempo lleva?', 'Depende del alcance, las integraciones y el estado del contenido. Con un brief inicial puedo proponerte etapas, entregables y una estimación ajustada al proyecto.'],
 ['¿Podemos seguir trabajando después del lanzamiento?', 'Sí. Podemos acordar una etapa de mantenimiento y evolución para incorporar funcionalidades, revisar el rendimiento y acompañar las necesidades del negocio.'],
];
