import Link from 'next/link';
import {ArrowDown, ArrowUpRight, ArrowRight, Asterisk, Code2} from 'lucide-react';
import {Nav} from '@/components/nav';
import {Motion} from '@/components/motion';
import {IdentityBadge} from '@/components/identity-badge';
import {Brief} from '@/components/brief';
import {ProjectArt} from '@/components/project-art';
import {projects, services, faqs, siteUrl} from '@/lib/content';
export default function Home(){return <><Nav/><Motion/><main id="contenido">
 <section className="hero"><div className="hero-meta"><span><i className="status-dot"/> DESARROLLO & ESTRATEGIA DIGITAL</span><span>ARGENTINA · TRABAJO SIN FRONTERAS ↗</span></div><div className="hero-main"><h1><span className="hero-line"><span>Ideas que</span></span><span className="hero-line"><span>se vuelven</span></span><span className="hero-line accent"><span>digitales<span className="period">.</span></span></span></h1><div className="hero-art"><IdentityBadge/></div></div><div className="hero-bottom"><div className="hero-description"><span className="tiny-cross">+</span><p>Soy Mau. Conecto diseño, código y negocio<br className="desktop-break"/> para crear <strong>experiencias que hacen la diferencia.</strong></p></div><div className="hero-actions"><a className="button primary" href="#proyectos">Explorá mis proyectos <ArrowDown size={18}/></a><span className="scroll-hint">SCROLL PARA DESCUBRIR</span></div></div><div className="hero-foot"><span>MAGENTO &nbsp; / &nbsp; NEXT.JS &nbsp; / &nbsp; WOOCOMMERCE</span><span>ESTRATEGIA → CÓDIGO → IMPACTO</span></div></section>
 <div className="ticker" aria-hidden="true"><div className="ticker-track">{Array.from({length:4},(_,i)=><span key={i}>BUEN DISEÑO <Asterisk/> CÓDIGO CON PROPÓSITO <Asterisk/> IDEAS EN MOVIMIENTO <Asterisk/></span>)}</div></div>
 <section className="section projects" id="proyectos"><div className="section-label" data-reveal><span>01 / TRABAJO SELECCIONADO</span><span>DE LA IDEA A LA REALIDAD ↙</span></div><div className="section-heading" data-reveal><h2>Menos bla.<br/>Más <em>hecho.</em></h2><p>Cada proyecto, un desafío distinto.<br/>La misma intención: construir algo<br/>que tenga sentido para el negocio.</p></div><div className="project-grid">{projects.map(p=><Link className={`project-card ${p.color}`} key={p.slug} href={`/proyectos/${p.slug}`} data-reveal><ProjectArt slug={p.slug}/><div className="project-info"><div><span className="eyebrow">{p.category}</span><h3>{p.name}<span className="project-number">/{p.number}</span></h3></div><span className="project-arrow"><ArrowUpRight/></span></div><p className="project-summary">{p.description}</p><div className="project-tags">{p.stack.slice(0,3).map(t=><span key={t}>{t}</span>)}<span className="case-link">Ver proyecto ↗</span></div></Link>)}</div></section>
 <section className="services section" id="servicios"><div className="section-label" data-reveal><span>02 / LO QUE PUEDO HACER POR VOS</span><Code2 size={21}/></div><div className="section-heading" data-reveal><h2>Tu próximo paso.<br/><em>Lo construimos.</em></h2><p>Del primer lanzamiento a la evolución<br/>de una plataforma. Tecnología elegida<br/>para resolver tu desafío.</p></div><div className="service-list">{services.map((s,i)=><article className="service-row" key={s.title} data-reveal><span className="service-num">0{i+1}</span><div><span className="eyebrow">{s.tags}</span><h3>{s.title}</h3><p>{s.text}</p></div><ul>{s.items.map(x=><li key={x}><ArrowRight size={14}/>{x}</li>)}</ul><a href="#contacto" aria-label={`Consultar por ${s.title}`}><ArrowUpRight/></a></article>)}</div></section>
 <section className="about section" id="sobre-mi"><div className="about-art" data-reveal><div className="code-mark">&lt;m<span>m</span>/&gt;</div><div className="about-art-foot"><span>MENTALIDAD CREATIVA.<br/>BASE TÉCNICA.</span><Asterisk size={52}/></div></div><div className="about-copy" data-reveal><span className="eyebrow">03 / DETRÁS DEL CÓDIGO</span><h2>Hola, soy Mau.<br/>Me gusta hacer<br/><em>que las cosas pasen.</em></h2><p>Trabajo donde se cruzan la tecnología, el diseño y los problemas reales de un negocio.</p><p>Mi experiencia conecta el e-commerce con Magento y WooCommerce, y el desarrollo de productos desde cero con Next.js. Desde una tienda hasta una plataforma inmobiliaria con su propia gestión.</p><p>Hoy sigo construyendo y evolucionando ese ecosistema: catálogos, integraciones, experiencias de compra y herramientas que simplifican el trabajo diario.</p><a className="text-link" href="https://www.instagram.com/maumorell/" target="_blank" rel="noopener noreferrer">Un poco más de mí en Instagram <ArrowUpRight size={18}/></a></div></section>
 <section className="process section"><div className="section-label" data-reveal><span>04 / CÓMO TRABAJAMOS</span><span>CLARIDAD EN CADA ETAPA</span></div><h2 data-reveal>Un buen proceso.<br/><em>Un mejor resultado.</em></h2><div className="process-grid">{[['Entender','Conversamos sobre tu negocio, tus usuarios y lo que necesitás resolver. El objetivo va primero.'],['Definir','Ordenamos prioridades, alcance y entregables. Vas a saber qué vamos a construir y por qué.'],['Construir','Diseño y desarrollo en etapas, con avances visibles y espacio para tomar decisiones juntos.'],['Evolucionar','Validamos, lanzamos y definimos los próximos pasos a partir del uso real de la plataforma.']].map(([title,text],i)=><article key={title} data-reveal><span>0{i+1}<ArrowUpRight size={20}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="faq section"><div data-reveal><span className="eyebrow">05 / ANTES DE EMPEZAR</span><h2>Buenas<br/><em>preguntas.</em></h2></div><div className="faq-items" data-reveal>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="contact section" id="contacto"><div data-reveal><span className="eyebrow"><i className="status-dot"/> HAGAMOS LUGAR A TU PRÓXIMA IDEA</span><h2>¿Y si lo<br/><em>hacemos</em><br/>realidad<span>?</span></h2><p>Contame en qué estás pensando.<br/>El primer paso es una buena conversación.</p><a className="text-link" href="https://www.instagram.com/maumorell/" target="_blank" rel="noopener noreferrer">@maumorell <ArrowUpRight size={18}/></a></div><Brief/></section>
 </main><footer className="footer"><a className="wordmark" href="#">mau<span>morell</span><b>✳</b></a><span>DISEÑADO CON INTENCIÓN. CONSTRUIDO CON CÓDIGO.</span><span>© {new Date().getFullYear()} Maumorell</span><a href="#" aria-label="Volver al inicio">↑</a></footer>{siteUrl&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Person',name:'Maumorell',url:siteUrl,sameAs:['https://www.instagram.com/maumorell/'],knowsAbout:['Next.js','Magento','WooCommerce','Desarrollo web','E-commerce']}).replace(/</g,'\\u003c')}}/>}</>}